export const STATIC_TRANSLATIONS = {
  en: {
    // Navigation & Header
    Dashboard: "Dashboard",
    Sales: "Sales",
    Inventory: "Inventory",
    Expenses: "Expenses",
    Customers: "Customers",
    Clients: "Clients",
    Analytics: "Analytics",
    Reports: "Reports",
    Payments: "Payments",
    Settings: "Settings",
    Profile: "Profile",
    Schedule: "Schedule",
    Team: "Team",
    Services: "Services",
    "Sign in": "Sign in",
    "Sign up": "Sign up",
    "Sign out": "Sign out",
    Features: "Features",
    Pricing: "Pricing",
    Solutions: "Solutions",
    "Public Listings": "Public Listings",

    // Common Actions
    Create: "Create",
    Edit: "Edit",
    Delete: "Delete",
    Save: "Save",
    Cancel: "Cancel",
    Submit: "Submit",
    Update: "Update",
    Add: "Add",
    Remove: "Remove",
    Export: "Export",
    Import: "Import",
    Search: "Search",
    Filter: "Filter",
    Sort: "Sort",
    View: "View",
    Download: "Download",
    Print: "Print",
    Refresh: "Refresh",
    Back: "Back",
    Next: "Next",
    Previous: "Previous",
    Close: "Close",
    Apply: "Apply",
    Clear: "Clear",
    Reset: "Reset",
    "Get Started": "Get Started",

    // Common Fields
    Name: "Name",
    Email: "Email",
    Phone: "Phone",
    Address: "Address",
    City: "City",
    State: "State",
    Country: "Country",
    "Zip Code": "Zip Code",
    Date: "Date",
    "Start Date": "Start Date",
    "End Date": "End Date",
    Amount: "Amount",
    Price: "Price",
    Quantity: "Quantity",
    Total: "Total",
    Status: "Status",
    Description: "Description",
    Notes: "Notes",
    Category: "Category",
    Type: "Type",
    Created: "Created",
    Updated: "Updated",

    // Dashboard
    "Welcome to Dashboard": "Welcome to Dashboard",
    "Monthly Revenue": "Monthly Revenue",
    "Total Customers": "Total Customers",
    "Stock Value": "Stock Value",
    "Low Stock Items": "Low Stock Items",
    "Recent Activity": "Recent Activity",
    "Quick Actions": "Quick Actions",
    "Revenue Trend": "Revenue Trend",
    "Top Products": "Top Products",
    "Sales Summary": "Sales Summary",

    // Sales
    "Add Sale": "Add Sale",
    "Sale Details": "Sale Details",
    "Sale Date": "Sale Date",
    "Paid Amount": "Paid Amount",
    "Outstanding Amount": "Outstanding Amount",
    "Payment Status": "Payment Status",
    "Payment Method": "Payment Method",
    "Invoice Number": "Invoice Number",
    "Sales Report": "Sales Report",
    "Sales Statistics": "Sales Statistics",

    // Inventory
    "Add Product": "Add Product",
    "Product Details": "Product Details",
    "Product Name": "Product Name",
    "Product Code": "Product Code",
    "SKU": "SKU",
    "Stock Quantity": "Stock Quantity",
    "Min Stock Level": "Min Stock Level",
    "Reorder Level": "Reorder Level",
    "Unit Price": "Unit Price",
    "Cost Price": "Cost Price",
    "Supplier": "Supplier",
    "Inventory Report": "Inventory Report",
    "Stock Movement": "Stock Movement",
    "Low Stock Alert": "Low Stock Alert",

    // Expenses
    "Add Expense": "Add Expense",
    "Expense Details": "Expense Details",
    "Expense Category": "Expense Category",
    "Expense Date": "Expense Date",
    "Expense Amount": "Expense Amount",
    "Paid By": "Paid By",
    "Expense Report": "Expense Report",
    "Monthly Expenses": "Monthly Expenses",

    // Customers
    "Add Customer": "Add Customer",
    "Customer Details": "Customer Details",
    "Customer Name": "Customer Name",
    "Customer Email": "Customer Email",
    "Customer Phone": "Customer Phone",
    "Customer Address": "Customer Address",
    "Customer Since": "Customer Since",
    "Total Purchases": "Total Purchases",
    "Account Balance": "Account Balance",

    // Clients
    "Add Client": "Add Client",
    "Client Details": "Client Details",
    "Client Name": "Client Name",
    "Client Email": "Client Email",
    "Client Phone": "Client Phone",
    "Client Company": "Client Company",
    "Contact Person": "Contact Person",

    // Payments
    "Payment Details": "Payment Details",
    "Payment Date": "Payment Date",
    "Payment Amount": "Payment Amount",
    "Payment Method": "Payment Method",
    "Reference Number": "Reference Number",
    "Transaction ID": "Transaction ID",
    "Payment Status": "Payment Status",
    "Pending": "Pending",
    "Completed": "Completed",
    "Failed": "Failed",
    "Cancelled": "Cancelled",

    // Analytics
    "Analytics Dashboard": "Analytics Dashboard",
    "Revenue Overview": "Revenue Overview",
    "Customer Trends": "Customer Trends",
    "Product Performance": "Product Performance",
    "Sales Forecast": "Sales Forecast",

    // Reports
    "Generate Report": "Generate Report",
    "Report Type": "Report Type",
    "Report Period": "Report Period",
    "Daily Report": "Daily Report",
    "Weekly Report": "Weekly Report",
    "Monthly Report": "Monthly Report",
    "Annual Report": "Annual Report",

    // Settings
    "Account Settings": "Account Settings",
    "Business Settings": "Business Settings",
    "System Settings": "System Settings",
    "Change Password": "Change Password",
    "Current Password": "Current Password",
    "New Password": "New Password",
    "Confirm Password": "Confirm Password",
    "Language": "Language",
    "Theme": "Theme",
    "Light": "Light",
    "Dark": "Dark",

    // Messages
    "Loading...": "Loading...",
    "Error": "Error",
    "Success": "Success",
    "Warning": "Warning",
    "Info": "Info",
    "Confirm": "Confirm",
    "Are you sure?": "Are you sure?",
    "No data available": "No data available",
    "Something went wrong": "Something went wrong",
    "Saved successfully": "Saved successfully",
    "Deleted successfully": "Deleted successfully",
    "Updated successfully": "Updated successfully",
    "Created successfully": "Created successfully",
    "Failed to save": "Failed to save",
    "Failed to delete": "Failed to delete",
    "Failed to update": "Failed to update",

    // Authentication
    "Login": "Login",
    "Register": "Register",
    "Username": "Username",
    "Password": "Password",
    "Remember me": "Remember me",
    "Forgot password?": "Forgot password?",
    "Create account": "Create account",
    "Already have an account?": "Already have an account?",
    "Don't have an account?": "Don't have an account?",
    "Signing in": "Signing in",
    "Enter your credentials to access your dashboard": "Enter your credentials to access your dashboard",
    "Send reset link": "Send reset link",
    "Email address": "Email address",
    "Hide": "Hide",
    "Show": "Show",
    "Signed in successfully": "Signed in successfully",
    "Phone number": "Phone number",
    "Creating account": "Creating account",
    "Please fill required fields": "Please fill required fields",
    "Use at least 8 characters with a mix of letters and numbers": "Use at least 8 characters with a mix of letters and numbers",
    "Everything you need to manage your business": "Everything you need to manage your business",
    "Script combines invoicing, inventory, analytics, team management, and customer tools into one simple platform — designed specifically for Nigerian product sellers.": "Script combines invoicing, inventory, analytics, team management, and customer tools into one simple platform — designed specifically for Nigerian product sellers.",
    "Built for Nigerian businesses": "Built for Nigerian businesses",
    "Local Payment Integration": "Local Payment Integration",
    "Seamlessly integrate with Nigerian payment systems including Flutterwave, local bank transfers, and USSD payments.": "Seamlessly integrate with Nigerian payment systems including Flutterwave, local bank transfers, and USSD payments.",
    "Naira currency support": "Naira currency support",
    "Local tax format compliance": "Local tax format compliance",
    "Multiple payment gateway options": "Multiple payment gateway options",
    "Optimized Performance": "Optimized Performance",
    "Designed to work efficiently even with slower internet connections. Lightweight, fast, and reliable.": "Designed to work efficiently even with slower internet connections. Lightweight, fast, and reliable.",
    "Works offline with sync": "Works offline with sync",
    "Mobile-optimized interface": "Mobile-optimized interface",
    "Fast loading times": "Fast loading times",
    "Practical Workflows": "Practical Workflows",
    "Built from real feedback from Nigerian business owners. Workflows designed for practical, everyday business needs.": "Built from real feedback from Nigerian business owners. Workflows designed for practical, everyday business needs.",
    "Quick data entry": "Quick data entry",
    "Bulk operations": "Bulk operations",
    "Smart defaults": "Smart defaults",
    "Enterprise Security": "Enterprise Security",
    "Your business data is protected with bank-level security, regular backups, and compliance standards.": "Your business data is protected with bank-level security, regular backups, and compliance standards.",
    "99.9% uptime guarantee": "99.9% uptime guarantee",
    "Automatic daily backups": "Automatic daily backups",
    "Everything in one place": "Everything in one place",
    "Feature": "Feature",
    "Included": "Included",
    "Unlimited invoice creation and templates": "Unlimited invoice creation and templates",
    "Unlimited inventory management": "Unlimited inventory management",
    "Customer database and management": "Customer database and management",
    "Up to unlimited team members": "Up to unlimited team members",
    "Payment and transaction tracking": "Payment and transaction tracking",
    "Expense management and budgeting": "Expense management and budgeting",
    "Sales analytics and insights": "Sales analytics and insights",
    "Mobile app access": "Mobile app access",
    "API access for integrations": "API access for integrations",
    "Data export in multiple formats": "Data export in multiple formats",
    "24/7 priority support": "24/7 priority support",
    "Ready to transform your business?": "Ready to transform your business?",
    "Start managing your business with Script today.": "Start managing your business with Script today.",
    "View pricing": "View pricing",
    "Welcome back": "Welcome back",
    "Here's a quick look at your product business": "Here's a quick look at your product business",
    "This Month": "This Month",
    "sales": "sales",
    "expenses": "expenses",
    "Stock levels": "Stock levels",
    "Low": "Low",
    "InStock": "InStock",
    "Total items": "Total items",
    "Profit": "Profit",
    "Unknown item": "Unknown item",
    "Sale": "Sale",
    "No recent activity": "No recent activity",
    "Quick actions": "Quick actions",
    "Add New Product": "Add New Product",
    "See Expenses": "See Expenses",
    "Add New Sale": "Add New Sale",
    "New sale": "New sale",
    "Record and review sales. Creating a sale will update inventory counts": "Record and review sales. Creating a sale will update inventory counts",
    "Sales copied (JSON)": "Sales copied (JSON)",
    "Item not found": "Item not found",
    "Enter a valid quantity": "Enter a valid quantity",
    "Not enough stock": "Not enough stock",
    "Sale recorded": "Sale recorded",
    "Record sale": "Record sale",
    "Available": "Available",
    "Customer": "Customer",
    "New sale": "New sale",
    "Qty": "Qty",
    "sales": "sales",

    // Business Info
    "Business Name": "Business Name",
    "Business Email": "Business Email",
    "Business Phone": "Business Phone",
    "Business Address": "Business Address",
    "Tax ID": "Tax ID",
    "Business License": "Business License",

    // Subscription
    "Plan": "Plan",
    "Select Plan": "Select Plan",
    "Subscribe": "Subscribe",
    "Upgrade": "Upgrade",
    "Downgrade": "Downgrade",
    "Monthly": "Monthly",
    "Annual": "Annual",
    "Free": "Free",
    "Pro": "Pro",
    "Enterprise": "Enterprise",

    // Admin
    "Admin Dashboard": "Admin Dashboard",
    "User Management": "User Management",
    "Tenant Management": "Tenant Management",
    "System Configuration": "System Configuration",
    "Security & Compliance": "Security & Compliance",
    "API Management": "API Management",
    "Billing Control": "Billing Control",
    "Support Center": "Support Center",
    "Analytics": "Analytics",

    // Landing Page
    "Script — Smart Business Management System for Nigerian SMEs": "Script — Smart Business Management System for Nigerian SMEs",
    "All-in-one platform to manage sales, inventory, cash flow, and customer relationships — built for businesses in Nigeria with local payments and practical workflows": "All-in-one platform to manage sales, inventory, cash flow, and customer relationships — built for businesses in Nigeria with local payments and practical workflows",
    "Get started — ₦200/month": "Get started — ₦200/month",
    "See all features": "See all features",
    "Everything you need to run your business": "Everything you need to run your business",
    "Sales Management": "Sales Management",
    "Create sales, track payments, and manage stock levels reminders": "Create sales, track payments, and manage stock levels reminders",
    "Inventory Tracking": "Inventory Tracking",
    "Monitor stock levels, set reorder points, track inventory value, and manage product variations": "Monitor stock levels, set reorder points, track inventory value, and manage product variations",
    "Advanced Analytics": "Advanced Analytics",
    "Get detailed insights into sales trends, revenue, expenses, and business performance metrics": "Get detailed insights into sales trends, revenue, expenses, and business performance metrics",
    "Customer Management": "Customer Management",
    "Centralize customer data, track communication history, and manage customer relationships": "Centralize customer data, track communication history, and manage customer relationships",
    "Team Collaboration": "Team Collaboration",
    "Add team members, assign roles, delegate tasks, and collaborate seamlessly with your team": "Add team members, assign roles, delegate tasks, and collaborate seamlessly with your team",
    "Secure & Reliable": "Secure & Reliable",
    "Enterprise-grade security, regular backups, and 99.9% uptime guarantee for your business data": "Enterprise-grade security, regular backups, and 99.9% uptime guarantee for your business data",
    "Built for Nigerian businesses": "Built for Nigerian businesses",
    "Local payment integration with Nigerian banks and Flutterwave": "Local payment integration with Nigerian banks and Flutterwave",
    "Support for Nigerian Naira (₦) currency and local tax formats": "Support for Nigerian Naira (₦) currency and local tax formats",
    "Optimized for slow internet with offline-capable features": "Optimized for slow internet with offline-capable features",
    "Practical workflows designed from real Nigerian business needs": "Practical workflows designed from real Nigerian business needs",
    "Affordable pricing that grows with your business": "Affordable pricing that grows with your business",
    "Active businesses": "Active businesses",
    "Tracked in sales": "Tracked in sales",
    "Uptime guarantee": "Uptime guarantee",

    // Expenses
    "Track and manage your business expenses": "Track and manage your business expenses",
    "Add Expense": "Add Expense",
    "This Month": "This Month",
    "expenses": "expenses",
    "Total Expenses": "Total Expenses",
    "expenses recorded": "expenses recorded",
    "Average per Expense": "Average per Expense",
    "All time average": "All time average",
    "New Expense": "New Expense",
    "Add a new expense to track your costs": "Add a new expense to track your costs",
    "Description": "Description",
    "e.g., Monthly electricity bill": "e.g., Monthly electricity bill",
    "Amount": "Amount",
    "Category": "Category",
    "Date": "Date",
    "Save Expense": "Save Expense",
    "Expenses by Category": "Expenses by Category",
    "transactions": "transactions",
    "No expenses recorded yet. Add your first expense to get started": "No expenses recorded yet. Add your first expense to get started",

    // Analytics
    "Loading analytics": "Loading analytics",
    "Comprehensive business metrics and sales performance analysis": "Comprehensive business metrics and sales performance analysis",
    "Total Annual Sales": "Total Annual Sales",
    "Across 12 months": "Across 12 months",
    "Average Monthly Sales": "Average Monthly Sales",
    "Year to date average": "Year to date average",
    "Best Performing Month": "Best Performing Month",
    "Above target": "Above target",
    "Below target": "Below target",
    "Lowest Performing Month": "Lowest Performing Month",
    "Monthly Sales Performance": "Monthly Sales Performance",

    // Inventory
    "Track stock levels and manage products": "Track stock levels and manage products",
    "New product": "New product",
    "Inventory limit reached for your plan. Upgrade to Premium to add more products": "Inventory limit reached for your plan. Upgrade to Premium to add more products",
    "Export and detailed statistics are available on Premium only. Upgrade to access": "Export and detailed statistics are available on Premium only. Upgrade to access",
    "Please fill in all fields": "Please fill in all fields",
    "Inventory limit reached for your plan. Upgrade to Premium for unlimited inventory": "Inventory limit reached for your plan. Upgrade to Premium for unlimited inventory",
    "Please specify pieces per product": "Please specify pieces per product",
    "Please specify price per piece": "Please specify price per piece",
    "Please specify bulk price": "Please specify bulk price",
    "Invalid expense ID": "Invalid expense ID",
    "Expense deleted": "Expense deleted",
    "Expense added successfully": "Expense added successfully",

    // Common Status
    "Active": "Active",
    "Inactive": "Inactive",
    "Archived": "Archived",
    "Draft": "Draft",
    "Published": "Published",
  },
  ha: {
    // Navigation & Header
    Dashboard: "Gida",
    Sales: "Siyarwa",
    Inventory: "Kaya Kiwo",
    Expenses: "Kasua",
    Customers: "Abokan Ciki",
    Clients: "Abokan Ciki",
    Analytics: "Nazari",
    Reports: "Rahotanni",
    Payments: "Biyan Kudin",
    Settings: "Saiti",
    Profile: "Bayani",
    Schedule: "Jadawali",
    Team: "Ƙungiya",
    Services: "Ayyuka",
    "Sign in": "Shiga Ciki",
    "Sign up": "Bugi",
    "Sign out": "Fita",
    Features: "Fasaloni",
    Pricing: "Farashin",
    Solutions: "Magani",
    "Public Listings": "Jerin Jama'a",

    // Common Actions
    Create: "Ƙirƙira",
    Edit: "Gyara",
    Delete: "Cire",
    Save: "Ajiye",
    Cancel: "Soke",
    Submit: "Gabatar",
    Update: "Sabunta",
    Add: "Ƙara",
    Remove: "Cire",
    Export: "Fita",
    Import: "Shiga",
    Search: "Nemi",
    Filter: "Tace",
    Sort: "Tsari",
    View: "Gani",
    Download: "Saukar",
    Print: "Bugi",
    Refresh: "Sabunta",
    Back: "Koma",
    Next: "Gida",
    Previous: "Baya",
    Close: "Rufe",
    Apply: "Aiwata",
    Clear: "Sace",
    Reset: "Maimaita",
    "Get Started": "Fara",

    // Common Fields
    Name: "Suna",
    Email: "Gida da Jiya",
    Phone: "Waya",
    Address: "Adireshi",
    City: "Gari",
    State: "Jiha",
    Country: "Kasuwa",
    "Zip Code": "Lambar Kudin",
    Date: "Kwanan",
    "Start Date": "Farkon Kwanan",
    "End Date": "Ƙarshen Kwanan",
    Amount: "Adadi",
    Price: "Farashi",
    Quantity: "Yawa",
    Total: "Jami'a",
    Status: "Yanayin",
    Description: "Bayanin",
    Notes: "Sanarwa",
    Category: "Rukuni",
    Type: "Nau'i",
    Created: "An Ƙirƙira",
    Updated: "An Sabunta",

    // Dashboard
    "Welcome to Dashboard": "Sannu da Zuwa Gida",
    "Monthly Revenue": "Kudin Wata",
    "Total Customers": "Duka Abokan Ciki",
    "Stock Value": "Kimar Kaya",
    "Low Stock Items": "Kayan Kasuwa Kasuwa",
    "Recent Activity": "Ayyukan Kwanan",
    "Quick Actions": "Ayyukan Sauri",
    "Revenue Trend": "Tashen Kudin",
    "Top Products": "Kayan Ari",
    "Sales Summary": "Taƙaitaccen Siyarwa",

    // Sales
    "Add Sale": "Ƙara Siyarwa",
    "Sale Details": "Bayanin Siyarwa",
    "Sale Date": "Kwanan Siyarwa",
    "Paid Amount": "Kudin da Aka Biya",
    "Outstanding Amount": "Kudin Da Ke Jira",
    "Payment Status": "Yanayin Biya",
    "Payment Method": "Hanyar Biya",
    "Invoice Number": "Lambar Kwaicewa",
    "Sales Report": "Rahoton Siyarwa",
    "Sales Statistics": "Yanayin Siyarwa",

    // Inventory
    "Add Product": "Ƙara Kayan",
    "Product Details": "Bayanin Kayan",
    "Product Name": "Sunan Kayan",
    "Product Code": "Lambar Kayan",
    "SKU": "SKU",
    "Stock Quantity": "Adadin Kaya",
    "Min Stock Level": "Mafi Kasuwa Kaya",
    "Reorder Level": "Tsarin Saka",
    "Unit Price": "Farashi Gida",
    "Cost Price": "Farashi Kasua",
    "Supplier": "Mai Shidar Kaya",
    "Inventory Report": "Rahoton Kaya",
    "Stock Movement": "Motsin Kaya",
    "Low Stock Alert": "Gida Kasuwa Kaya",

    // Expenses
    "Add Expense": "Ƙara Kasua",
    "Expense Details": "Bayanin Kasua",
    "Expense Category": "Nau'in Kasua",
    "Expense Date": "Kwanan Kasua",
    "Expense Amount": "Kudin Kasua",
    "Paid By": "An Biya Ta",
    "Expense Report": "Rahoton Kasua",
    "Monthly Expenses": "Kasuan Wata",

    // Customers
    "Add Customer": "Ƙara Abokin Ciki",
    "Customer Details": "Bayanin Abokin Ciki",
    "Customer Name": "Sunan Abokin Ciki",
    "Customer Email": "Gida da Jiya na Abokin Ciki",
    "Customer Phone": "Wayan Abokin Ciki",
    "Customer Address": "Adireshi na Abokin Ciki",
    "Customer Since": "Tun Lokacin Abokin Ciki",
    "Total Purchases": "Duka Sayen",
    "Account Balance": "Jiya Asusun",

    // Clients
    "Add Client": "Ƙara Abokin Ciki",
    "Client Details": "Bayanin Abokin Ciki",
    "Client Name": "Sunan Abokin Ciki",
    "Client Email": "Gida da Jiya na Abokin Ciki",
    "Client Phone": "Wayan Abokin Ciki",
    "Client Company": "Kamfanin Abokin Ciki",
    "Contact Person": "Mutumin Sadarwa",

    // Payments
    "Payment Details": "Bayanin Biya",
    "Payment Date": "Kwanan Biya",
    "Payment Amount": "Kudin Biya",
    "Payment Method": "Hanyar Biya",
    "Reference Number": "Lambar Sanarwa",
    "Transaction ID": "Lambar Musayar",
    "Payment Status": "Yanayin Biya",
    "Pending": "Jira",
    "Completed": "Kammala",
    "Failed": "Gazava",
    "Cancelled": "Soke",

    // Analytics
    "Analytics Dashboard": "Gidan Nazari",
    "Revenue Overview": "Takaita Kudin",
    "Customer Trends": "Tashen Abokan Ciki",
    "Product Performance": "Aikin Kayan",
    "Sales Forecast": "Hasashen Siyarwa",

    // Reports
    "Generate Report": "Ƙirƙira Rahoton",
    "Report Type": "Nau'in Rahoton",
    "Report Period": "Lokacin Rahoton",
    "Daily Report": "Rahoton Kwanan",
    "Weekly Report": "Rahoton Mako",
    "Monthly Report": "Rahoton Wata",
    "Annual Report": "Rahoton Shekara",

    // Settings
    "Account Settings": "Saiti Asusun",
    "Business Settings": "Saiti Kasuwa",
    "System Settings": "Saiti Tsarin",
    "Change Password": "Canja Kalmar Sirri",
    "Current Password": "Kalmar Sirri Ta Yanzu",
    "New Password": "Sabuwar Kalmar Sirri",
    "Confirm Password": "Tabbatar da Kalmar Sirri",
    "Language": "Harshe",
    "Theme": "Jiya",
    "Light": "Haske",
    "Dark": "Duhu",

    // Messages
    "Loading...": "Ana Lodi...",
    "Error": "Kuskure",
    "Success": "Nasara",
    "Warning": "Gida",
    "Info": "Bayanin",
    "Confirm": "Tabbatar",
    "Are you sure?": "Kina Tiyata?",
    "No data available": "Babu Bayani",
    "Something went wrong": "Wani Abu Ya Dace",
    "Saved successfully": "An Ajiye Nasara",
    "Deleted successfully": "An Cire Nasara",
    "Updated successfully": "An Sabunta Nasara",
    "Created successfully": "An Ƙirƙira Nasara",
    "Failed to save": "Gazava Ajiyar",
    "Failed to delete": "Gazava Cirar",
    "Failed to update": "Gazava Sabuntar",

    // Authentication
    "Login": "Shiga Ciki",
    "Register": "Bugi",
    "Username": "Sunan Mai Amfani",
    "Password": "Kalmar Sirri",
    "Remember me": "Tunai Ni",
    "Forgot password?": "Kin Manta da Kalmar Sirri?",
    "Create account": "Ƙirƙira Asusun",
    "Already have an account?": "Kina da Asusun?",
    "Don't have an account?": "Kina ba da Asusun?",
    "Signing in": "Ana Shigowa",
    "Enter your credentials to access your dashboard": "Shigar da asusunka don samun damar gida",
    "Send reset link": "Aika linki na sake saita",
    "Email address": "Adireshi Gida da Jiya",
    "Hide": "Boye",
    "Show": "Nuna",
    "Signed in successfully": "An Shiga Nasara",
    "Phone number": "Lambar Waya",
    "Creating account": "Ana Ƙirƙira Asusun",
    "Please fill required fields": "Wadda dole ne ka cika filayen",
    "Use at least 8 characters with a mix of letters and numbers": "Yi amfani da aƙalla haruffa 8 tare da haɗa wajen haruffa da lambobi",
    "Everything you need to manage your business": "Duk abin da kake bukowa don sarrafa kasuwa",
    "Script combines invoicing, inventory, analytics, team management, and customer tools into one simple platform — designed specifically for Nigerian product sellers.": "Script yana haɗa kwaicewa, kaya, nazari, sarrafa ƙungiya, da kayan abokan ciki a cikin gida ɗaya mai sauƙi — wanda aka ƙirƙira ne musamman don masu siyarwa na Nigeria.",
    "Built for Nigerian businesses": "An gina don kasuwancin Nigeria",
    "Local Payment Integration": "Haɗa Biya ta Gida",
    "Seamlessly integrate with Nigerian payment systems including Flutterwave, local bank transfers, and USSD payments.": "A niki haɗa da tsarin biya na Nigeria ciki har da Flutterwave, juyewa da gida, da biya ta USSD.",
    "Naira currency support": "Goyon bayan kudin Naira",
    "Local tax format compliance": "Aiwatar da tsari na haraji gida",
    "Multiple payment gateway options": "Zaɓi gateway biya mai yawa",
    "Optimized Performance": "Ingantacce Aiki",
    "Designed to work efficiently even with slower internet connections. Lightweight, fast, and reliable.": "An ƙirƙira don aiki da kimiya har da sauƙin haɗi. Mafi kasuwa, sauri, da amincin.",
    "Works offline with sync": "Yana aiki offline tare da sync",
    "Mobile-optimized interface": "Interface da aka inganta don Mobile",
    "Fast loading times": "Lokut bugi mafi sauri",
    "Practical Workflows": "Ayyukan Gida",
    "Built from real feedback from Nigerian business owners. Workflows designed for practical, everyday business needs.": "Gina daga ainihi feedback daga mai kasuwa na Nigeria. Ayyukan da aka ƙirƙira ne don bukawan kasuwa gida.",
    "Quick data entry": "Sauran shigar da bayani",
    "Bulk operations": "Ayyukan girma",
    "Smart defaults": "Zaɓi masu hankali",
    "Enterprise Security": "Tsaro na Kamfani",
    "Your business data is protected with bank-level security, regular backups, and compliance standards.": "Bayanin kasuwa ne a kariya tare da tsaro na gidan banki, rukunan jiya, da tsarin aiwata.",
    "99.9% uptime guarantee": "Garantin bugi 99.9%",
    "Automatic daily backups": "Rukunan jiya na yau da kullun",
    "Everything in one place": "Duk abin gida",
    "Feature": "Sifa",
    "Included": "Samma",
    "Unlimited invoice creation and templates": "Walang hanggang ƙirƙira kwaicewa da tsare",
    "Unlimited inventory management": "Walang hanggang sarrafa kaya",
    "Customer database and management": "Bayanan abokan ciki da sarrafa",
    "Up to unlimited team members": "Har zuwa walang hanggang kayan ƙungiya",
    "Payment and transaction tracking": "Biya da suturon musayar",
    "Expense management and budgeting": "Sarrafa kasua da ƙirataccen kudin",
    "Sales analytics and insights": "Nazarin siyarwa da albarka",
    "Mobile app access": "Samun app na Mobile",
    "API access for integrations": "Samun API don haɗi",
    "Data export in multiple formats": "Fita bayani a musamman-samaniya",
    "24/7 priority support": "Goyon bayan gida 24/7",
    "Ready to transform your business?": "Kina shirye don juyar da kasuwa?",
    "Start managing your business with Script today.": "Fara sarrafa kasuwa tare da Script jiya.",
    "View pricing": "Gani farashi",
    "Welcome back": "Sannu da zuwa",
    "Here's a quick look at your product business": "Ga saurin gani kasuwa na kayan",
    "This Month": "Wata",
    "sales": "siyarwa",
    "expenses": "kasua",
    "Stock levels": "Matakan kaya",
    "Low": "Kasuwa",
    "InStock": "Akwai kaya",
    "Total items": "Duka kayan",
    "Profit": "Riba",
    "Unknown item": "Kayan da ba a sani",
    "Sale": "Siyarwa",
    "No recent activity": "Babu ayyukan kwanan",
    "Quick actions": "Ayyukan sauri",
    "Add New Product": "Ƙara Sabuwar Kayan",
    "See Expenses": "Gani Kasua",
    "Add New Sale": "Ƙara Sabuwar Siyarwa",
    "New sale": "Sabuwar siyarwa",
    "Record and review sales. Creating a sale will update inventory counts": "Rubuta da sake duba siyarwa. Ƙirƙira siyarwa za ta sabunta adadin kaya.",
    "Sales copied (JSON)": "Siyarwa an jifa (JSON)",
    "Item not found": "Ba a tarar kayan",
    "Enter a valid quantity": "Shigar da adidin da ya dace",
    "Not enough stock": "Babu isasshen kaya",
    "Sale recorded": "An rubuta siyarwa",
    "Record sale": "Rubuta siyarwa",
    "Available": "Akwai",
    "Customer": "Abokin ciki",
    "New sale": "Sabuwar siyarwa",
    "Qty": "Yawa",
    "sales": "siyarwa",

    // Landing Page
    "Script — Smart Business Management System for Nigerian SMEs": "Script — Tsarin Jallaba Kasuwanchi don Kasuwancin Kasuwa a Nijeriya",
    "All-in-one platform to manage sales, inventory, cash flow, and customer relationships — built for businesses in Nigeria with local payments and practical workflows": "Platform ɗaya gida don sarrafa siyarwa, kaya, kudin kuɗi, da alaƙa da abokan ciki — an gina don kasuwanci a Nijeriya tare da biyan kudin gida da aiki na aiki",
    "Get started — ₦200/month": "Fara — ₦200/wata",
    "See all features": "Duba duk fasaloji",
    "Everything you need to run your business": "Duka abin da kake buƙu don aiki da kasuwancin ku",
    "Sales Management": "Jallaba Siyarwa",
    "Create sales, track payments, and manage stock levels reminders": "Ƙirƙira siyarwa, lura da biyan kudin, da sarrafa sanarwa matakin jarin",
    "Inventory Tracking": "Lura da Jarin Kaya",
    "Monitor stock levels, set reorder points, track inventory value, and manage product variations": "Lura da matakin jarin, saita lokacin sake oda, lura da ƙimar jarin, da sarrafa bambance-bambancen kayoyi",
    "Advanced Analytics": "Nazari mai ci gaba",
    "Get detailed insights into sales trends, revenue, expenses, and business performance metrics": "Samu bayanai cikakke kan yunin siyarwa, kudaden kuɗi, kasua, da ma'aunin aiki kasuwanchi",
    "Customer Management": "Jallaba Abokan Ciki",
    "Centralize customer data, track communication history, and manage customer relationships": "Tattara bayanin abokan ciki, lura da tarihin sadarwa, da sarrafa alaƙa da abokan ciki",
    "Team Collaboration": "Haɗin Gwiwa",
    "Add team members, assign roles, delegate tasks, and collaborate seamlessly with your team": "Ƙara membobin gida, sanya aiki, ba aiki, da haɗu sosai da gidanku",
    "Secure & Reliable": "Ligine & Aminci",
    "Enterprise-grade security, regular backups, and 99.9% uptime guarantee for your business data": "Amincin kasuwan, ajiyar ajiya ta yau da kullun, da garantiya na 99.9% tare da aiki don bayanan kasuwancin ku",
    "Built for Nigerian businesses": "An gina don kasuwancin Nijeriya",
    "Local payment integration with Nigerian banks and Flutterwave": "Haɗin biyan kudin gida tare da bankunan Nijeriya da Flutterwave",
    "Support for Nigerian Naira (₦) currency and local tax formats": "Goyon bayan Naira na Nijeriya (₦) da tsarin haraji na gida",
    "Optimized for slow internet with offline-capable features": "An daidaita don sabon intanet mai niyya tare da abubuwa da za su aiki ba tare da intanet ba",
    "Practical workflows designed from real Nigerian business needs": "Aiki na aiki da aka zana daga tunani na ainihi na kasuwancin Nijeriya",
    "Affordable pricing that grows with your business": "Farashin da ya takaici wanda ya karu tare da kasuwancin ku",
    "Active businesses": "Kasuwanci masu aiki",
    "Tracked in sales": "Lura a cikin siyarwa",
    "Uptime guarantee": "Garantiya na aiki",

    // Expenses
    "Track and manage your business expenses": "Lura da sarrafa kasuan kasuwancin ku",
    "Add Expense": "Ƙara Kasua",
    "This Month": "Watan Nan",
    "expenses": "kasua",
    "Total Expenses": "Jimillar Kasua",
    "expenses recorded": "kasua da aka rubuta",
    "Average per Expense": "Matsakaci bisa kasua",
    "All time average": "Matsakacin dukkan lokuta",
    "New Expense": "Sabuwar Kasua",
    "Add a new expense to track your costs": "Ƙara sabuwar kasua don lura da kudaden ku",
    "Description": "Bayanin",
    "e.g., Monthly electricity bill": "misali, Kasuan watawar lantarki",
    "Amount": "Adadi",
    "Category": "Nau'iyya",
    "Date": "Kwanan",
    "Save Expense": "Ajiye Kasua",
    "Expenses by Category": "Kasua ta hanyar Nau'iyya",
    "transactions": "jerin ayyuka",
    "No expenses recorded yet. Add your first expense to get started": "Ba a rubuta kasua ba. Ƙara kasua ta farko don fara",

    // Analytics
    "Loading analytics": "Loda nazari",
    "Comprehensive business metrics and sales performance analysis": "Cikakken ma'aunin kasuwanchi da nazarin abubuwan siyarwa",
    "Total Annual Sales": "Jimillar Siyarwa na Shekara",
    "Across 12 months": "A cikin watanni 12",
    "Average Monthly Sales": "Matsakacin Siyarwa na Wata",
    "Year to date average": "Matsakacin tun shekara zuwa yau",
    "Best Performing Month": "Watan Aiki Mai Kyau",
    "Above target": "Sama da manufa",
    "Below target": "Ƙasa da manufa",
    "Lowest Performing Month": "Watan Aiki Mafi Ƙanƙanci",
    "Monthly Sales Performance": "Abubuwan Siyarwa na Wata",

    // Inventory
    "Track stock levels and manage products": "Lura da matakin jarin kaya da sarrafa kayoyi",
    "New product": "Sabuwar kaya",
    "Inventory limit reached for your plan. Upgrade to Premium to add more products": "An kai iyaka ga jerin kayan kuɗin kula. Ƙari zuwa Premium don ƙara kayoyi",
    "Export and detailed statistics are available on Premium only. Upgrade to access": "Fitar da ƙarin bayanai suke kan Premium kawai. Ƙari don shiga",
    "Please fill in all fields": "Da fada kuna bugi duka",
    "Inventory limit reached for your plan. Upgrade to Premium for unlimited inventory": "An kai iyaka ga jerin kayan kuɗin kula. Ƙari zuwa Premium don marasa iyaka",
    "Please specify pieces per product": "Da fada kuna bugi adadin gine-gine bisa kaya",
    "Please specify price per piece": "Da fada kuna bugi farashin gine-gine",
    "Please specify bulk price": "Da fada kuna bugi farashin aje",
    "Invalid expense ID": "ID kasua wanda ba shi aiki ba",
    "Expense deleted": "An gida kasua",
    "Expense added successfully": "An ƙara kasua sosai",

    // Business Info
    "Business Name": "Sunan Kasuwa",
    "Business Email": "Gida da Jiya na Kasuwa",
    "Business Phone": "Wayan Kasuwa",
    "Business Address": "Adireshi na Kasuwa",
    "Tax ID": "Lambar Haraji",
    "Business License": "Lasisi Kasuwa",

    // Subscription
    "Plan": "Tsarin",
    "Select Plan": "Zaɓi Tsarin",
    "Subscribe": "Bugi",
    "Upgrade": "Ƙari",
    "Downgrade": "Rage",
    "Monthly": "Wata",
    "Annual": "Shekara",
    "Free": "Kyauta",
    "Pro": "Pro",
    "Enterprise": "Kasuwa",

    // Admin
    "Admin Dashboard": "Gidan Gidar",
    "User Management": "Jallaba Mai Amfani",
    "Tenant Management": "Jallaba Mai Gida",
    "System Configuration": "Tsarin Saiti",
    "Security & Compliance": "Tsaro da Aiwata",
    "API Management": "Jallaba API",
    "Billing Control": "Sarrafa Biya",
    "Support Center": "Cibiyar Goyon Baya",
    "Analytics": "Nazari",

    // Common Status
    "Active": "Aiki",
    "Inactive": "Tsayawa",
    "Archived": "Ajiye",
    "Draft": "Shiryewa",
    "Published": "Shaida",
  },
};
